### PR TITLE
"Get new codes here" functionality, plus SSP 1.15

### PR DESCRIPTION
**Pull request by longrunningprocess**
@fillup waiting on decision regarding https://github.com/silinternational/simplesamlphp-module-material/issues/54 before mergin to `master`

### CODE REVIEW

**Comment by forevermatt** [comment]
Just so that we're all aware, we need to wait to merge this until we finish checking (and where necessary, updating) our SimpleSAMLphp modules to work with simplesamlphp 1.15.

**Comment by forevermatt** [comment]
I think we're finally ready to cut a new release (minor version bump, I think) of `ssp-base`. @fillup / @wcjr / @Baggerone, does that sound right to you?

**Comment by forevermatt** [comment]
Okay, this seems to be working fine on the staging hub. I think we're ready to release.

**Comment by forevermatt** [comment]
As far as I can tell, it's time to release and tag this update to ssp-base. @wcjr @Baggerone @fillup Any objections?

**Comment by Baggerone** [comment]
If the new version of simplesamlphp is a breaking change, why wouldn't this be considered one also?

**Comment by forevermatt** [comment]
@Baggerone made some interesting points as we were discussing this:
- Since simplesamlphp is designed to allow using custom modules, and switching from 1.14 to 1.15 does (I think unintentionally) include a backwards breaking change affecting any modules using the old namespacing in `instanceof` or typehints, that seems to suggest this should be a major version bump.
- Is there any reason _not_ to bump the major version? I can't necessarily think of one (since, depending on what you're "measure", this does break some backwards compatibility).

@fillup Thoughts?

**Comment by wcjr** [comment]
I agree, it should be a major then.  You never know if someone might be relying on our base or not...

**Comment by fillup** [comment]
Thats fine, major that is.

**Pull request merged**
